### ISSUE TITLE
User Register Function

### ISSUE THREAD

**Issue by aung-zan** [aung-zan/sale#6]
## Description
Enable user to register.

## Task List
- [x] Normal way.
- [ ] Social Media way.

**Comment by chaidul** [comment]
i can do user registation functionality.
please contact my email [technicalgyanassam@gmail.com](technicalgyanassam@gmail.com)

**Comment by aung-zan** [comment]
> i can do user registation functionality. please contact my email **[technicalgyanassam@gmail.com](mailto:technicalgyanassam@gmail.com)**

Thank you for interesting in my repo but I create this repo for self study and it's been a very long time that I don't use this repo.  I will contact to you if I need help in future. Thank you.

**Comment by chaidul** [comment]
Ok🤗
